spring.application.name=rentora

#Database Connection - POSTGRESQL
spring.datasource.url=jdbc:postgresql://localhost:5432/rentora_db
spring.datasource.username=rentora_user
spring.datasource.password=rentorapwd


#Hibernate JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

file.upload.dir = uploads/electricity-bills